@startuml SBD

class HeaderVersion
{
    String HeaderVersion
}

class Sender
{
    String Identifier
    String Authority
}

class Receiver
{
    String Identifier
    String Authority
}

class DocumentInformation
{
    String Standard
    String TypeVersion
    String InstanceIdentifier
    String Type
    String MultipleType
    String CreationDateAndTime
}

class BusinessScope
{
    Class Scope
}

class "StandardBusinessDocumentHeader" as ehmiSbdh<<SBD Header (SBDH)>>
class "HeaderVersion" as HeaderVersion <<ehmiSbdhelement>>
class "Sender" as Sender <<ehmiSbdhelement>>
class "Receiver" as Receiver <<ehmiSbdhelement>>
class "DocumentInformation" as DocumentInformation <<ehmiSbdhelement>>
class "BusinessScope" as BusinessScope <<ehmiSbdhelement>>


ehmiSbdh"1" *-- "1" HeaderVersion 
ehmiSbdh"1" *-- "1" Sender 
ehmiSbdh"1" *-- "1" Receiver 
ehmiSbdh"1" *-- "1" DocumentInformation 
ehmiSbdh"1" *-- "1" BusinessScope 


@enduml
