@startuml SBD

hide empty members

class BusinessScope
{
}

class Scope
{
    String Type
    String InstanceIdentifier
    String Identifier
}

Class CorrelationInformation
{
    DateTime RequestingDocumentCreationDateTime
    Identifier RequestingDocumentInstanceIdentifier
    DateTime ExpectedResponseDateTime
}

Class BusinessService
{
    String BusinessServiceName
}

Class ServiceTransaction
{
    String TypeOfServiceTransaction
    String IsNonRepudiationRequired
    String IsAuthenticationRequired
    String IsNonRepudiationOfReceiptRequired
    String IsIntelligibleCheckRequired 
    String IsApplicationErrorResponseRequested
    String TimeToAcknowledgeReceipt
    String TimeToAcknowledgeAcceptance
    String TimeToPerform
    String Recurrence
  
}

class "BusinessScope" as BusinessScope <<ehmiSbdhElement>>
class "Scope" as Scope <<BusinessScope Element>>
class "CorrelationInformation" as CorrelationInformation <<Scope Element>>
class "BusinessService" as BusinessService <<Scope Element>>
class "ServiceTransaction" as ServiceTransaction <<BusinessService Element>>

BusinessScope "1" *-- "0..*" Scope
Scope "1" *-- "0..1" CorrelationInformation
Scope "1" *-- "0..1" BusinessService
BusinessService "1" *-- "0..1" ServiceTransaction

@enduml
